FROM ubuntu:16.04

RUN apt-get -y update
RUN apt-get -y install cmake build-essential g++ wget git clang
RUN apt-get -y install libboost-all-dev uuid-dev
RUN apt-get -y install libssl-dev libjansson-dev automake pkg-config doxygen autoconf llvm check libtool make
